--INSERT PARAMETROS
INSERT INTO appvisitame.tvisita001_cfg_paramet (cd_parametro,nb_etiqueta,nb_glosa,tx_valor,cd_creador,tm_creacion) VALUES ('RADIO_ALCANCE_APP','PARAMETRO DE ALCANCE MAPA DEL APP VISITAME','Corresponde al radio de alcance para la busqueda en el mapa del app de visitas.','3',1,{ts '2017-06-21 10:21:16.789203'});

--INSERT LISTA VALORES
INSERT INTO appvisitame.tvisita002_cfg_lista (cd_lista,cd_alterno,nb_etiqueta,nb_glosa,st_estado,cd_creador,tm_creacion,cd_editor,tm_edicion) VALUES ( (SELECT nextval('appvisitame.seq_tvisita002_cfg_lista')) ,'PERSON_DOI_TIPO','Tipos de DOI de persona','dssd','A',1,'2017-06-19 00:00:00',null,null);
INSERT INTO appvisitame.tvisita002_cfg_lista (cd_lista,cd_alterno,nb_etiqueta,nb_glosa,st_estado,cd_creador,tm_creacion,cd_editor,tm_edicion) VALUES ( (SELECT nextval('appvisitame.seq_tvisita002_cfg_lista')) ,'PARAMETROS_INIT','PARAMETROS INICIALES DEL APP','PARAMETROS INICIALES DEL APP','A',1,'2017-06-06 12:00:00',null,null);
INSERT INTO appvisitame.tvisita002_cfg_lista (cd_lista,cd_alterno,nb_etiqueta,nb_glosa,st_estado,cd_creador,tm_creacion,cd_editor,tm_edicion) VALUES ( (SELECT nextval('appvisitame.seq_tvisita002_cfg_lista')) ,'PERSON_TIPO','Tipos de persona','Tipos de persona','A',1,'2017-06-06 12:00:00',null,null);

--INSERT VALORES
INSERT INTO appvisitame.tvisita003_cfg_valor (cd_valor,cd_padre,cd_lista,cd_alterno,nb_etiqueta,nb_glosa,nb_valor,nu_orden,st_estado,cd_creador,tm_creacion,cd_editor,tm_edicion) VALUES ( (SELECT nextval('appvisitame.seq_tvisita003_cfg_valor')) ,null,(SELECT CD_LISTA FROM appvisitame.tvisita002_cfg_lista WHERE CD_ALTERNO='PERSON_DOI_TIPO'),'E','EXT','Carnet de extranjeria','E',1,'A',1,{ts '2017-06-19 00:00:00'},null,null);
INSERT INTO appvisitame.tvisita003_cfg_valor (cd_valor,cd_padre,cd_lista,cd_alterno,nb_etiqueta,nb_glosa,nb_valor,nu_orden,st_estado,cd_creador,tm_creacion,cd_editor,tm_edicion) VALUES ( (SELECT nextval('appvisitame.seq_tvisita003_cfg_valor')) ,null,(SELECT CD_LISTA FROM appvisitame.tvisita002_cfg_lista WHERE CD_ALTERNO='PERSON_DOI_TIPO'),'L','DNI','Documento Nacional de Identidad','L',1,'A',1,{ts '2017-06-19 00:00:00'},null,null);
INSERT INTO appvisitame.tvisita003_cfg_valor (cd_valor,cd_padre,cd_lista,cd_alterno,nb_etiqueta,nb_glosa,nb_valor,nu_orden,st_estado,cd_creador,tm_creacion,cd_editor,tm_edicion) VALUES ( (SELECT nextval('appvisitame.seq_tvisita003_cfg_valor')) ,null,(SELECT CD_LISTA FROM appvisitame.tvisita002_cfg_lista WHERE CD_ALTERNO='PARAMETROS_INIT'),'ZOOM_MAP_GEN','ZOOM_MAP_GEN','Zoom del mapa general','16',2,'A',1,{ts '2017-06-23 13:14:39.248000'},null,null);
INSERT INTO appvisitame.tvisita003_cfg_valor (cd_valor,cd_padre,cd_lista,cd_alterno,nb_etiqueta,nb_glosa,nb_valor,nu_orden,st_estado,cd_creador,tm_creacion,cd_editor,tm_edicion) VALUES ( (SELECT nextval('appvisitame.seq_tvisita003_cfg_valor')) ,null,(SELECT CD_LISTA FROM appvisitame.tvisita002_cfg_lista WHERE CD_ALTERNO='PARAMETROS_INIT'),'RAD_ALCANCE','RAD_ALCANCE','Radio alcance busqueda mapa app visitame','3000',1,'A',1,{ts '2017-06-06 12:00:00'},null,null);
INSERT INTO appvisitame.tvisita003_cfg_valor (cd_valor,cd_padre,cd_lista,cd_alterno,nb_etiqueta,nb_glosa,nb_valor,nu_orden,st_estado,cd_creador,tm_creacion,cd_editor,tm_edicion) VALUES ( (SELECT nextval('appvisitame.seq_tvisita003_cfg_valor')) ,null,(SELECT CD_LISTA FROM appvisitame.tvisita002_cfg_lista WHERE CD_ALTERNO='PERSON_TIPO'),'PN','Natural','Persona natural','PN',2,'A',1,{ts '2017-06-23 13:14:39.248000'},null,null);
INSERT INTO appvisitame.tvisita003_cfg_valor (cd_valor,cd_padre,cd_lista,cd_alterno,nb_etiqueta,nb_glosa,nb_valor,nu_orden,st_estado,cd_creador,tm_creacion,cd_editor,tm_edicion) VALUES ( (SELECT nextval('appvisitame.seq_tvisita003_cfg_valor')) ,null,(SELECT CD_LISTA FROM appvisitame.tvisita002_cfg_lista WHERE CD_ALTERNO='PERSON_TIPO'),'PJ','Jurídica','Persona jurídica','PJ',1,'A',1,{ts '2017-06-06 12:00:00'},null,null);

COMMIT;